### ISSUE TITLE
Checking the wrong property for Driver name.

### ISSUE THREAD

**Issue by codespikey** [ibelousov/advanced-nested-set#4]
https://github.com/ibelousov/advanced-nested-set/blob/78d1da3fc2c451da098515046c77c5febae32840/src/AdvancedNestedSet.php#L33-L34
The `getDriverName` function should be used instead of `getName`.

**Comment by ibelousov** [comment]
> https://github.com/ibelousov/advanced-nested-set/blob/78d1da3fc2c451da098515046c77c5febae32840/src/AdvancedNestedSet.php#L33-L34
> 
> 
> The `getDriverName` function should be used instead of `getName`.

Thank you, i fixed it

[src/AdvancedNestedSet.php](https://github.com/ibelousov/advanced-nested-set/blob/10667677955dbcd459511dd24caf8f62eeec6ff0/src/AdvancedNestedSet.php#L33-L34)
